apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: "box.com/v1"
kind: Pki
metadata:
  name: app1-pki
  namespace: app1
spec:
  # This service name has a typo
  serviceName: appp1





